import 'package:uuid/uuid.dart';

import '../../network/api_exceptions.dart';
import 'connectivity_service.dart';
import 'sync_service.dart';

/// Shared helper that wraps repository mutation calls with offline-queue support.
///
/// Online path: calls [remoteCall] directly and returns its result.
/// Offline / network-error path: enqueues via [SyncService.queueMutation],
/// then returns an optimistic result so the UI can proceed without blocking.
///
/// #1117: every queued write carries an idempotency key so its replay dedupes on
/// the server. When the initial online attempt reached the server but timed out,
/// the key generated by `IdempotencyInterceptor` rides back on the thrown
/// [ApiException] — [queueCall] persists THAT key so the replay matches. When the
/// device is offline (no attempt made) a fresh key is generated here.
class MutationQueueHelper {
  MutationQueueHelper({
    required ConnectivityService connectivity,
    required SyncService syncService,
    Uuid uuid = const Uuid(),
  }) : _connectivity = connectivity,
       _syncService = syncService,
       _uuid = uuid;

  final ConnectivityService _connectivity;
  final SyncService _syncService;
  final Uuid _uuid;

  /// Execute a mutation that returns [T].
  ///
  /// - [remoteCall]: the actual API call via RemoteRepository.
  /// - [queueCall]: enqueues the mutation via [SyncService], attaching the
  ///   supplied idempotency key to the queue entry.
  /// - [optimisticResult]: fabricates an immediate return value for offline use.
  Future<T> executeMutation<T>({
    required Future<T> Function() remoteCall,
    required Future<void> Function(
      SyncService syncService,
      String idempotencyKey,
    )
    queueCall,
    required T Function() optimisticResult,
  }) async {
    final offlineKey = _uuid.v4();
    final online = await _connectivity.isOnline;

    if (!online) {
      await queueCall(_syncService, offlineKey);
      return optimisticResult();
    }

    try {
      return await remoteCall();
    } on Exception catch (e) {
      if (_isNetworkFailure(e)) {
        await queueCall(_syncService, _keyFor(e) ?? offlineKey);
        return optimisticResult();
      }
      rethrow;
    }
  }

  /// Execute a void mutation (delete, cancel, archive, etc.)
  Future<void> executeVoidMutation({
    required Future<void> Function() remoteCall,
    required Future<void> Function(
      SyncService syncService,
      String idempotencyKey,
    )
    queueCall,
  }) async {
    final offlineKey = _uuid.v4();
    final online = await _connectivity.isOnline;

    if (!online) {
      await queueCall(_syncService, offlineKey);
      return;
    }

    try {
      await remoteCall();
    } on Exception catch (e) {
      if (_isNetworkFailure(e)) {
        await queueCall(_syncService, _keyFor(e) ?? offlineKey);
        return;
      }
      rethrow;
    }
  }

  /// The idempotency key the initial attempt used, if the interceptor attached
  /// one before the request failed.
  String? _keyFor(Exception e) => e is ApiException ? e.idempotencyKey : null;

  /// Returns true for exceptions that indicate network unavailability
  /// (should fall back to queue), false for business errors (should propagate).
  bool _isNetworkFailure(Exception e) {
    if (e is NetworkException) return true;
    if (e is ServerException) return true;
    if (e is ApiException && e.statusCode != null && e.statusCode! >= 500) {
      return true;
    }
    return false;
  }
}
