"""initial postgresql schema

Revision ID: 0001
Revises:
Create Date: 2026-03-11 00:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_time_slots',
    sa.Column('availability_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_slot_availability', 'availability_time_slots', ['availability_id'], unique=False)
    op.create_table('class_memberships',
    sa.Column('lesson_class_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'paused', 'terminated', name='membershipstatus'), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('monthly_fee', sa.Integer(), nullable=False),
    sa.Column('lessons_per_week', sa.Integer(), nullable=False),
    sa.Column('lesson_day', sa.String(length=10), nullable=True),
    sa.Column('lesson_time', sa.String(length=5), nullable=True),
    sa.Column('lesson_duration', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_membership_class', 'class_memberships', ['lesson_class_id'], unique=False)
    op.create_index('idx_membership_student', 'class_memberships', ['student_id'], unique=False)
    op.create_index('uk_membership_class_student', 'class_memberships', ['lesson_class_id', 'student_id'], unique=True)
    op.create_table('daily_practice_statuses',
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_date', 'daily_practice_statuses', ['date'], unique=False)
    op.create_index('uk_daily_section_date', 'daily_practice_statuses', ['section_id', 'date'], unique=True)
    op.create_table('follows',
    sa.Column('follower_id', sa.String(length=36), nullable=False),
    sa.Column('following_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.Enum('teacher', 'academy', name='followtargettype'), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_follow_following', 'follows', ['following_id'], unique=False)
    op.create_index('uk_follow', 'follows', ['follower_id', 'following_id'], unique=True)
    op.create_table('group_classes',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('regular', 'dropIn', name='groupclasstype'), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('waitlist_capacity', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('booking_deadline_minutes', sa.Integer(), nullable=False),
    sa.Column('cancel_deadline_minutes', sa.Integer(), nullable=False),
    sa.Column('no_show_policy', sa.Enum('deduct', 'noDeduct', name='noshowpolicy'), nullable=False),
    sa.Column('max_no_show_count', sa.Integer(), nullable=True),
    sa.Column('repeat_days', sa.JSON(), nullable=True),
    sa.Column('repeat_time', sa.String(length=5), nullable=True),
    sa.Column('instrument', sa.String(length=50), nullable=True),
    sa.Column('price_per_session', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_group_teacher', 'group_classes', ['teacher_id'], unique=False)
    op.create_table('i18n_translations',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('context', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_translation_context', 'i18n_translations', ['context'], unique=False)
    op.create_index('uk_translation_key_locale', 'i18n_translations', ['key', 'locale'], unique=True)
    op.create_table('lesson_bookings',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_type', sa.Enum('trial', 'regular', 'oneTime', name='bookinglessontype'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=5), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', 'completed', 'noShow', name='bookingstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_booking_date', 'lesson_bookings', ['scheduled_date'], unique=False)
    op.create_index('idx_booking_status', 'lesson_bookings', ['status'], unique=False)
    op.create_index('idx_booking_student', 'lesson_bookings', ['student_id'], unique=False)
    op.create_index('idx_booking_teacher', 'lesson_bookings', ['teacher_id'], unique=False)
    op.create_table('lesson_classes',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('academy', 'private', name='lessonclasstype'), nullable=False),
    sa.Column('payment_type', sa.Enum('organization', 'parent', name='paymenttype'), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_class_teacher', 'lesson_classes', ['teacher_id'], unique=False)
    op.create_table('lesson_locations',
    sa.Column('lesson_class_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('academyRoom', 'teacherStudio', 'studentHome', 'externalPlace', 'online', name='locationtype'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('online_platform', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_location_class', 'lesson_locations', ['lesson_class_id'], unique=False)
    op.create_table('lesson_pieces',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('composer', sa.String(length=100), nullable=True),
    sa.Column('opus', sa.String(length=50), nullable=True),
    sa.Column('movement', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_piece_lesson', 'lesson_pieces', ['lesson_id'], unique=False)
    op.create_table('lesson_policies',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('cancellation_deadline_hours', sa.Integer(), nullable=False),
    sa.Column('late_cancel_deducts_lesson', sa.Boolean(), nullable=False),
    sa.Column('no_show_deducts_lesson', sa.Boolean(), nullable=False),
    sa.Column('max_no_show_count', sa.Integer(), nullable=True),
    sa.Column('reschedule_allowed', sa.Boolean(), nullable=False),
    sa.Column('reschedule_deadline_hours', sa.Integer(), nullable=False),
    sa.Column('max_reschedule_per_subscription', sa.Integer(), nullable=False),
    sa.Column('makeup_expiry_days', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uk_policy_teacher', 'lesson_policies', ['teacher_id'], unique=True)
    op.create_table('lesson_recordings',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lesson_rec_lesson', 'lesson_recordings', ['lesson_id'], unique=False)
    op.create_table('lesson_requests',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('preferred_timing', sa.Enum('nextWeek', 'nextMonth', 'afterConsultation', name='requesttiming'), nullable=False),
    sa.Column('keep_previous_schedule', sa.Boolean(), nullable=False),
    sa.Column('previous_lesson_day', sa.Integer(), nullable=True),
    sa.Column('previous_lesson_time', sa.String(length=5), nullable=True),
    sa.Column('previous_lesson_duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'proposalSent', 'accepted', 'declined', 'expired', 'cancelled', name='requeststatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_request_status', 'lesson_requests', ['status'], unique=False)
    op.create_index('idx_request_student', 'lesson_requests', ['student_id'], unique=False)
    op.create_index('idx_request_teacher', 'lesson_requests', ['teacher_id'], unique=False)
    op.create_table('lessons',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('teacher_name', sa.String(length=100), nullable=True),
    sa.Column('instrument', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', 'cancelledByStudentAdvance', 'cancelledByStudentLate', 'cancelledByTeacher', 'cancelledMutual', 'noShow', 'studentAbsent', 'reschedulePending', name='lessonstatus'), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('practice_tips', sa.Text(), nullable=True),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lesson_date', 'lessons', ['date'], unique=False)
    op.create_index('idx_lesson_status', 'lessons', ['status'], unique=False)
    op.create_index('idx_lesson_student', 'lessons', ['student_id'], unique=False)
    op.create_index('idx_lesson_teacher', 'lessons', ['teacher_id'], unique=False)
    op.create_index('idx_lesson_teacher_date', 'lessons', ['teacher_id', 'date'], unique=False)
    op.create_table('makeup_lessons',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('original_lesson_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'scheduled', 'completed', 'expired', 'cancelled', name='makeupstatus'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.String(length=5), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_makeup_status', 'makeup_lessons', ['status'], unique=False)
    op.create_index('idx_makeup_student', 'makeup_lessons', ['student_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='notificationpriority'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_push', sa.Boolean(), nullable=False),
    sa.Column('is_in_app', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_created', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notif_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_index('idx_notif_user', 'notifications', ['user_id'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('google', 'kakao', 'apple', name='oauthprovider'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('is_private_email', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oauth_user_id', 'oauth_accounts', ['user_id'], unique=False)
    op.create_index('uk_oauth_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'], unique=True)
    op.create_table('parent_child_relations',
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.Enum('viewOnly', 'managePayments', 'manageLessons', 'fullAccess', name='parentpermission'), nullable=False),
    sa.Column('connected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uk_parent_child', 'parent_child_relations', ['parent_id', 'student_id'], unique=True)
    op.create_table('parent_teacher_connections',
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('permission', sa.Enum('viewOnly', 'managePayments', 'manageLessons', 'fullAccess', name='parentpermission'), nullable=False),
    sa.Column('connected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ptc_teacher', 'parent_teacher_connections', ['teacher_id'], unique=False)
    op.create_index('uk_parent_teacher', 'parent_teacher_connections', ['parent_id', 'teacher_id'], unique=True)
    op.create_table('parents',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('profile_color', sa.String(length=7), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'inactive', name='parentstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uk_parent_user_id', 'parents', ['user_id'], unique=True)
    op.create_table('payments',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('trial', 'regular', name='paymenttype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'confirmed', 'overdue', 'cancelled', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('method', sa.Enum('cash', 'bankTransfer', 'card', 'other', name='paymentmethodenum'), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('lesson_count', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('week_start', sa.Integer(), nullable=True),
    sa.Column('week_end', sa.Integer(), nullable=True),
    sa.Column('student_confirmed', sa.Boolean(), nullable=False),
    sa.Column('student_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('billing_target_type', sa.Enum('student', 'parent', name='billingtargettype'), nullable=False),
    sa.Column('billing_target_id', sa.String(length=36), nullable=True),
    sa.Column('billing_target_name', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_by', sa.String(length=36), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('parent_notified', sa.Boolean(), nullable=False),
    sa.Column('parent_notified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_due_date', 'payments', ['due_date'], unique=False)
    op.create_index('idx_payment_period', 'payments', ['period_start', 'period_end'], unique=False)
    op.create_index('idx_payment_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payment_student', 'payments', ['student_id'], unique=False)
    op.create_table('practice_goals',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('daily_time_minutes', sa.Integer(), nullable=False),
    sa.Column('daily_section_count', sa.Integer(), nullable=False),
    sa.Column('weekly_time_minutes', sa.Integer(), nullable=False),
    sa.Column('weekly_day_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uk_goal_student', 'practice_goals', ['student_id'], unique=True)
    op.create_table('practice_items',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('repertoire', 'technique', 'theory', 'custom', name='practiceitemtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repertoire_id', sa.String(length=36), nullable=True),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('priority', sa.Enum('must', 'should', 'could', name='practiceitempriority'), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('practice_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('has_like', sa.Boolean(), nullable=False),
    sa.Column('liked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_lesson', 'practice_items', ['lesson_id'], unique=False)
    op.create_index('idx_item_student', 'practice_items', ['student_id'], unique=False)
    op.create_index('idx_item_teacher', 'practice_items', ['teacher_id'], unique=False)
    op.create_table('practice_notes',
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_note_section', 'practice_notes', ['section_id'], unique=False)
    op.create_table('practice_recordings',
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('is_representative', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_practice_rec_section', 'practice_recordings', ['section_id'], unique=False)
    op.create_table('practice_repertoires',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_repertoire_dates', 'practice_repertoires', ['student_id', 'start_date', 'end_date'], unique=False)
    op.create_index('idx_repertoire_student', 'practice_repertoires', ['student_id'], unique=False)
    op.create_table('practice_sections',
    sa.Column('repertoire_id', sa.String(length=36), nullable=False),
    sa.Column('piece_name', sa.String(length=200), nullable=False),
    sa.Column('range_type', sa.Enum('full', 'line', 'measure', 'measures', name='rangetype'), nullable=False),
    sa.Column('start_measure', sa.Integer(), nullable=False),
    sa.Column('end_measure', sa.Integer(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(length=200), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_repeat', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('repeat_count', sa.Integer(), nullable=True),
    sa.Column('daily_repeat_counts', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('practice_count', sa.Integer(), nullable=False),
    sa.Column('total_practice_seconds', sa.Integer(), nullable=False),
    sa.Column('target_practice_seconds', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('last_practiced_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_section_completed', 'practice_sections', ['is_completed'], unique=False)
    op.create_index('idx_section_repertoire', 'practice_sections', ['repertoire_id'], unique=False)
    op.create_table('practice_streaks',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_practice_date', sa.Date(), nullable=True),
    sa.Column('total_practice_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uk_streak_student', 'practice_streaks', ['student_id'], unique=True)
    op.create_table('schedule_confirmation_cards',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', 'expired', name='confirmationcardstatus'), nullable=False),
    sa.Column('proposed_day', sa.String(length=10), nullable=True),
    sa.Column('proposed_time', sa.String(length=5), nullable=True),
    sa.Column('proposed_duration', sa.Integer(), nullable=True),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scc_status', 'schedule_confirmation_cards', ['status'], unique=False)
    op.create_index('idx_scc_student', 'schedule_confirmation_cards', ['student_id'], unique=False)
    op.create_index('idx_scc_teacher', 'schedule_confirmation_cards', ['teacher_id'], unique=False)
    op.create_table('students',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Enum('beginner', 'elementary', 'intermediate', 'advanced', name='studentlevel'), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'paused', 'inactive', name='studentstatus'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('parent_phone', sa.String(length=20), nullable=True),
    sa.Column('parent_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('age_group', sa.Enum('child', 'student', 'adult', name='agegroup'), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('profile_color', sa.String(length=7), nullable=True),
    sa.Column('monthly_fee', sa.Integer(), nullable=False),
    sa.Column('lessons_per_week', sa.Integer(), nullable=False),
    sa.Column('lesson_day', sa.String(length=10), nullable=True),
    sa.Column('lesson_time', sa.String(length=5), nullable=True),
    sa.Column('lesson_duration', sa.Integer(), nullable=False),
    sa.Column('connection_status', sa.Enum('offline', 'inviteSent', 'inviteReceived', 'connected', 'disconnected', name='connectionstatus'), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('practice_level', sa.Enum('newStudent', 'excellent', 'average', 'poor', 'onBreak', name='practicelevel'), nullable=True),
    sa.Column('break_reason', sa.Text(), nullable=True),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_students_connection', 'students', ['connection_status'], unique=False)
    op.create_index('idx_students_status', 'students', ['status'], unique=False)
    op.create_index('idx_students_teacher_id', 'students', ['teacher_id'], unique=False)
    op.create_index('idx_students_user_id', 'students', ['user_id'], unique=False)
    op.create_table('subscription_proposals',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paymentNotified', 'confirmed', 'rejected', 'expired', 'cancelled', name='proposalstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'completed', name='proposalpaymentstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('payment_notified_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('academy_id', sa.String(length=36), nullable=True),
    sa.Column('discount_amount', sa.Integer(), nullable=True),
    sa.Column('discount_reason', sa.Text(), nullable=True),
    sa.Column('template_ids', sa.JSON(), nullable=True),
    sa.Column('recommended_template_id', sa.String(length=36), nullable=True),
    sa.Column('selected_template_id', sa.String(length=36), nullable=True),
    sa.Column('is_auto_proposal', sa.Boolean(), nullable=False),
    sa.Column('is_app_transition', sa.Boolean(), nullable=False),
    sa.Column('lesson_request_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proposal_expires', 'subscription_proposals', ['expires_at'], unique=False)
    op.create_index('idx_proposal_status', 'subscription_proposals', ['status'], unique=False)
    op.create_index('idx_proposal_student', 'subscription_proposals', ['student_id'], unique=False)
    op.create_index('idx_proposal_teacher', 'subscription_proposals', ['teacher_id'], unique=False)
    op.create_table('subscription_templates',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('trial', 'monthly', 'package', name='subscriptiontype'), nullable=False),
    sa.Column('lessons_count', sa.Integer(), nullable=True),
    sa.Column('lessons_per_month', sa.Integer(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_teacher', 'subscription_templates', ['teacher_id'], unique=False)
    op.create_table('subscription_usages',
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('used_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('teacher_name', sa.String(length=100), nullable=True),
    sa.Column('instrument', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('lesson', 'noShow', 'cancellationPenalty', 'reschedule', 'bonus', 'manual', name='usagetype'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_date', 'subscription_usages', ['used_at'], unique=False)
    op.create_index('idx_usage_subscription', 'subscription_usages', ['subscription_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('membership_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('trial', 'monthly', 'package', name='subscriptiontype'), nullable=False),
    sa.Column('total_lessons', sa.Integer(), nullable=True),
    sa.Column('used_lessons', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expiringSoon', 'expired', 'paused', name='subscriptionstatus'), nullable=False),
    sa.Column('lessons_per_month', sa.Integer(), nullable=True),
    sa.Column('bonus_count', sa.Integer(), nullable=False),
    sa.Column('billing_type', sa.Enum('perPackage', 'monthly', name='billingtype'), nullable=True),
    sa.Column('billing_day', sa.Integer(), nullable=True),
    sa.Column('fifth_week_policy', sa.Enum('skip', 'bonus', 'deduct', 'optional', name='fifthweekpolicy'), nullable=True),
    sa.Column('bonus_reason', sa.Text(), nullable=True),
    sa.Column('total_reschedule_allowance', sa.Integer(), nullable=False),
    sa.Column('used_reschedule_count', sa.Integer(), nullable=False),
    sa.Column('payment_confirmed', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'bankTransfer', 'card', 'other', name='paymentmethod'), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('discount_amount', sa.Integer(), nullable=True),
    sa.Column('discount_reason', sa.Text(), nullable=True),
    sa.Column('original_amount', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sub_end_date', 'subscriptions', ['end_date'], unique=False)
    op.create_index('idx_sub_membership', 'subscriptions', ['membership_id'], unique=False)
    op.create_index('idx_sub_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_sub_student', 'subscriptions', ['student_id'], unique=False)
    op.create_table('supported_locales',
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('language_name', sa.String(length=50), nullable=False),
    sa.Column('native_name', sa.String(length=50), nullable=False),
    sa.Column('default_country', sa.String(length=2), nullable=False),
    sa.Column('default_timezone', sa.String(length=50), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('locale')
    )
    op.create_table('teacher_availabilities',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uk_avail_teacher_day', 'teacher_availabilities', ['teacher_id', 'day_of_week'], unique=True)
    op.create_table('teacher_careers',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_career_teacher', 'teacher_careers', ['teacher_id'], unique=False)
    op.create_table('teacher_certificates',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('musicTeacher', 'cultureArtsEducator', 'schoolTeacher', 'conservatory', 'degree', 'performance', 'other', name='certificatetype'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuing_body', sa.String(length=200), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='certificatestatus'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_certificate_status', 'teacher_certificates', ['status'], unique=False)
    op.create_index('idx_certificate_teacher', 'teacher_certificates', ['teacher_id'], unique=False)
    op.create_table('teacher_educations',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('school', sa.String(length=200), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('degree', sa.String(length=50), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_education_teacher', 'teacher_educations', ['teacher_id'], unique=False)
    op.create_table('teacher_student_relations',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'inactive', 'disconnected', name='relationstatus'), nullable=False),
    sa.Column('invite_code', sa.String(length=10), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_relation_status', 'teacher_student_relations', ['status'], unique=False)
    op.create_index('uk_relation_teacher_student', 'teacher_student_relations', ['teacher_id', 'student_id'], unique=True)
    op.create_table('teachers',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('instruments', sa.JSON(), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('lesson_areas', sa.JSON(), nullable=True),
    sa.Column('lesson_types', sa.JSON(), nullable=True),
    sa.Column('fee_min', sa.Integer(), nullable=True),
    sa.Column('fee_max', sa.Integer(), nullable=True),
    sa.Column('fee_duration', sa.Integer(), nullable=True),
    sa.Column('teaching_style', sa.Text(), nullable=True),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('portfolio_video_urls', sa.JSON(), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('account_holder', sa.String(length=50), nullable=True),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(), nullable=True),
    sa.Column('visibility_settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uk_teachers_user_id', 'teachers', ['user_id'], unique=True)
    op.create_table('tip_templates',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('technique', 'musicality', 'practice', 'mindset', 'general', name='tipcategory'), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tip_teacher', 'tip_templates', ['teacher_id'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_expires', 'token_blacklist', ['expires_at'], unique=False)
    op.create_index('uk_token_jti', 'token_blacklist', ['jti'], unique=True)
    op.create_table('tuition_settings',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('monthly_fee', sa.Integer(), nullable=False),
    sa.Column('lesson_fee', sa.Integer(), nullable=False),
    sa.Column('is_monthly_billing', sa.Boolean(), nullable=False),
    sa.Column('lessons_per_month', sa.Integer(), nullable=False),
    sa.Column('billing_day', sa.Integer(), nullable=False),
    sa.Column('preferred_method', sa.Enum('cash', 'bankTransfer', 'card', 'other', name='paymentmethodenum'), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('default_billing_target', sa.Enum('student', 'parent', name='billingtargettype'), nullable=False),
    sa.Column('default_billing_parent_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uk_tuition_student', 'tuition_settings', ['student_id'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('teacher', 'student', 'parent', name='userrole'), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_country', 'users', ['country'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('uk_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uk_users_email', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_country', table_name='users')
    op.drop_table('users')
    op.drop_index('uk_tuition_student', table_name='tuition_settings')
    op.drop_table('tuition_settings')
    op.drop_index('uk_token_jti', table_name='token_blacklist')
    op.drop_index('idx_token_expires', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index('idx_tip_teacher', table_name='tip_templates')
    op.drop_table('tip_templates')
    op.drop_index('uk_teachers_user_id', table_name='teachers')
    op.drop_table('teachers')
    op.drop_index('uk_relation_teacher_student', table_name='teacher_student_relations')
    op.drop_index('idx_relation_status', table_name='teacher_student_relations')
    op.drop_table('teacher_student_relations')
    op.drop_index('idx_education_teacher', table_name='teacher_educations')
    op.drop_table('teacher_educations')
    op.drop_index('idx_certificate_teacher', table_name='teacher_certificates')
    op.drop_index('idx_certificate_status', table_name='teacher_certificates')
    op.drop_table('teacher_certificates')
    op.drop_index('idx_career_teacher', table_name='teacher_careers')
    op.drop_table('teacher_careers')
    op.drop_index('uk_avail_teacher_day', table_name='teacher_availabilities')
    op.drop_table('teacher_availabilities')
    op.drop_table('supported_locales')
    op.drop_index('idx_sub_student', table_name='subscriptions')
    op.drop_index('idx_sub_status', table_name='subscriptions')
    op.drop_index('idx_sub_membership', table_name='subscriptions')
    op.drop_index('idx_sub_end_date', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_usage_subscription', table_name='subscription_usages')
    op.drop_index('idx_usage_date', table_name='subscription_usages')
    op.drop_table('subscription_usages')
    op.drop_index('idx_template_teacher', table_name='subscription_templates')
    op.drop_table('subscription_templates')
    op.drop_index('idx_proposal_teacher', table_name='subscription_proposals')
    op.drop_index('idx_proposal_student', table_name='subscription_proposals')
    op.drop_index('idx_proposal_status', table_name='subscription_proposals')
    op.drop_index('idx_proposal_expires', table_name='subscription_proposals')
    op.drop_table('subscription_proposals')
    op.drop_index('idx_students_user_id', table_name='students')
    op.drop_index('idx_students_teacher_id', table_name='students')
    op.drop_index('idx_students_status', table_name='students')
    op.drop_index('idx_students_connection', table_name='students')
    op.drop_table('students')
    op.drop_index('idx_scc_teacher', table_name='schedule_confirmation_cards')
    op.drop_index('idx_scc_student', table_name='schedule_confirmation_cards')
    op.drop_index('idx_scc_status', table_name='schedule_confirmation_cards')
    op.drop_table('schedule_confirmation_cards')
    op.drop_index('uk_streak_student', table_name='practice_streaks')
    op.drop_table('practice_streaks')
    op.drop_index('idx_section_repertoire', table_name='practice_sections')
    op.drop_index('idx_section_completed', table_name='practice_sections')
    op.drop_table('practice_sections')
    op.drop_index('idx_repertoire_student', table_name='practice_repertoires')
    op.drop_index('idx_repertoire_dates', table_name='practice_repertoires')
    op.drop_table('practice_repertoires')
    op.drop_index('idx_practice_rec_section', table_name='practice_recordings')
    op.drop_table('practice_recordings')
    op.drop_index('idx_note_section', table_name='practice_notes')
    op.drop_table('practice_notes')
    op.drop_index('idx_item_teacher', table_name='practice_items')
    op.drop_index('idx_item_student', table_name='practice_items')
    op.drop_index('idx_item_lesson', table_name='practice_items')
    op.drop_table('practice_items')
    op.drop_index('uk_goal_student', table_name='practice_goals')
    op.drop_table('practice_goals')
    op.drop_index('idx_payment_student', table_name='payments')
    op.drop_index('idx_payment_status', table_name='payments')
    op.drop_index('idx_payment_period', table_name='payments')
    op.drop_index('idx_payment_due_date', table_name='payments')
    op.drop_table('payments')
    op.drop_index('uk_parent_user_id', table_name='parents')
    op.drop_table('parents')
    op.drop_index('uk_parent_teacher', table_name='parent_teacher_connections')
    op.drop_index('idx_ptc_teacher', table_name='parent_teacher_connections')
    op.drop_table('parent_teacher_connections')
    op.drop_index('uk_parent_child', table_name='parent_child_relations')
    op.drop_table('parent_child_relations')
    op.drop_index('uk_oauth_provider_user', table_name='oauth_accounts')
    op.drop_index('idx_oauth_user_id', table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index('idx_notif_user', table_name='notifications')
    op.drop_index('idx_notif_read', table_name='notifications')
    op.drop_index('idx_notif_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_makeup_student', table_name='makeup_lessons')
    op.drop_index('idx_makeup_status', table_name='makeup_lessons')
    op.drop_table('makeup_lessons')
    op.drop_index('idx_lesson_teacher_date', table_name='lessons')
    op.drop_index('idx_lesson_teacher', table_name='lessons')
    op.drop_index('idx_lesson_student', table_name='lessons')
    op.drop_index('idx_lesson_status', table_name='lessons')
    op.drop_index('idx_lesson_date', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('idx_request_teacher', table_name='lesson_requests')
    op.drop_index('idx_request_student', table_name='lesson_requests')
    op.drop_index('idx_request_status', table_name='lesson_requests')
    op.drop_table('lesson_requests')
    op.drop_index('idx_lesson_rec_lesson', table_name='lesson_recordings')
    op.drop_table('lesson_recordings')
    op.drop_index('uk_policy_teacher', table_name='lesson_policies')
    op.drop_table('lesson_policies')
    op.drop_index('idx_piece_lesson', table_name='lesson_pieces')
    op.drop_table('lesson_pieces')
    op.drop_index('idx_location_class', table_name='lesson_locations')
    op.drop_table('lesson_locations')
    op.drop_index('idx_class_teacher', table_name='lesson_classes')
    op.drop_table('lesson_classes')
    op.drop_index('idx_booking_teacher', table_name='lesson_bookings')
    op.drop_index('idx_booking_student', table_name='lesson_bookings')
    op.drop_index('idx_booking_status', table_name='lesson_bookings')
    op.drop_index('idx_booking_date', table_name='lesson_bookings')
    op.drop_table('lesson_bookings')
    op.drop_index('uk_translation_key_locale', table_name='i18n_translations')
    op.drop_index('idx_translation_context', table_name='i18n_translations')
    op.drop_table('i18n_translations')
    op.drop_index('idx_group_teacher', table_name='group_classes')
    op.drop_table('group_classes')
    op.drop_index('uk_follow', table_name='follows')
    op.drop_index('idx_follow_following', table_name='follows')
    op.drop_table('follows')
    op.drop_index('uk_daily_section_date', table_name='daily_practice_statuses')
    op.drop_index('idx_daily_date', table_name='daily_practice_statuses')
    op.drop_table('daily_practice_statuses')
    op.drop_index('uk_membership_class_student', table_name='class_memberships')
    op.drop_index('idx_membership_student', table_name='class_memberships')
    op.drop_index('idx_membership_class', table_name='class_memberships')
    op.drop_table('class_memberships')
    op.drop_index('idx_slot_availability', table_name='availability_time_slots')
    op.drop_table('availability_time_slots')
    # ### end Alembic commands ###
