"""frontend-backend schema alignment phase2

Revision ID: e34fbc3ccb63
Revises: d91e939737d0
Create Date: 2026-03-29 03:02:16.066354+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34fbc3ccb63'
down_revision: Union[str, None] = 'd91e939737d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_requests', sa.Column('academy_id', sa.String(length=36), nullable=True))
    op.add_column('students', sa.Column('postal_code', sa.String(length=10), nullable=True))
    op.add_column('students', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('address_detail', sa.String(length=200), nullable=True))
    op.add_column('students', sa.Column('district', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'district')
    op.drop_column('students', 'address_detail')
    op.drop_column('students', 'address')
    op.drop_column('students', 'postal_code')
    op.drop_column('lesson_requests', 'academy_id')
    # ### end Alembic commands ###
