"""add bank_accounts column to teachers

Revision ID: d91e939737d0
Revises: 0006
Create Date: 2026-03-29 02:04:24.354968+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd91e939737d0'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lesson_locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('lesson_requests', sa.Column('request_type', sa.String(length=20), nullable=True))
    op.add_column('lesson_requests', sa.Column('instrument', sa.String(length=50), nullable=True))
    op.add_column('lesson_requests', sa.Column('goal', sa.String(length=20), nullable=True))
    op.add_column('lesson_requests', sa.Column('experience_level', sa.String(length=20), nullable=True))
    op.add_column('lesson_requests', sa.Column('preferred_day', sa.Integer(), nullable=True))
    op.add_column('lesson_requests', sa.Column('preferred_time', sa.String(length=5), nullable=True))
    op.add_column('lesson_requests', sa.Column('preferred_duration', sa.Integer(), nullable=True))
    op.add_column('lesson_requests', sa.Column('is_returning_student', sa.Boolean(), nullable=False))
    op.add_column('lesson_requests', sa.Column('time_proposals', sa.JSON(), nullable=True))
    op.add_column('lesson_requests', sa.Column('current_round', sa.Integer(), nullable=False))
    op.add_column('lesson_requests', sa.Column('suggested_price', sa.Integer(), nullable=True))
    op.add_column('lesson_requests', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lesson_requests', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('lesson_requests', 'preferred_timing',
               existing_type=postgresql.ENUM('nextWeek', 'nextMonth', 'afterConsultation', name='requesttiming'),
               type_=sa.String(length=30),
               nullable=True)
    op.alter_column('lesson_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'proposalSent', 'accepted', 'declined', 'expired', 'cancelled', name='requeststatus'),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.add_column('teacher_settings', sa.Column('lesson_price_table', sa.JSON(), nullable=True))
    op.add_column('teacher_settings', sa.Column('trial_lesson_free', sa.Boolean(), nullable=False))
    op.add_column('teachers', sa.Column('bank_accounts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'bank_accounts')
    op.drop_column('teacher_settings', 'trial_lesson_free')
    op.drop_column('teacher_settings', 'lesson_price_table')
    op.alter_column('lesson_requests', 'status',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('pending', 'proposalSent', 'accepted', 'declined', 'expired', 'cancelled', name='requeststatus'),
               existing_nullable=False)
    op.alter_column('lesson_requests', 'preferred_timing',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('nextWeek', 'nextMonth', 'afterConsultation', name='requesttiming'),
               nullable=False)
    op.drop_column('lesson_requests', 'cancelled_at')
    op.drop_column('lesson_requests', 'confirmed_at')
    op.drop_column('lesson_requests', 'suggested_price')
    op.drop_column('lesson_requests', 'current_round')
    op.drop_column('lesson_requests', 'time_proposals')
    op.drop_column('lesson_requests', 'is_returning_student')
    op.drop_column('lesson_requests', 'preferred_duration')
    op.drop_column('lesson_requests', 'preferred_time')
    op.drop_column('lesson_requests', 'preferred_day')
    op.drop_column('lesson_requests', 'experience_level')
    op.drop_column('lesson_requests', 'goal')
    op.drop_column('lesson_requests', 'instrument')
    op.drop_column('lesson_requests', 'request_type')
    op.alter_column('lesson_locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('lesson_locations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
