import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:lessonaza/core/l10n/app_strings.dart';
import 'package:lessonaza/features/schedule/domain/entities/vacation_period.dart';
import 'package:lessonaza/features/schedule/domain/repositories/vacation_repository.dart';
import 'package:lessonaza/features/schedule/presentation/providers/vacation_providers.dart';
import 'package:lessonaza/features/schedule/presentation/screens/teacher_vacation_mode_screen.dart';

/// Tests for #929 (A4 가시성): vacation notify dialog.
///
/// After a successful vacation registration, the screen must show how many
/// students were notified. This is a pure FE visibility change — actual
/// notification dispatch is a BE concern (out of scope).
///
/// Spec: The dialog body text is generated by AppStrings.vacationNotifyDialogBody.

// ---------------------------------------------------------------------------
// Stub repository helpers
// ---------------------------------------------------------------------------

/// Repository stub that records the call and returns a batch with one period.
class _SubmitSuccessStub implements VacationRepository {
  final int impactedStudentCount;

  _SubmitSuccessStub({this.impactedStudentCount = 3});

  @override
  Future<VacationImpactPreview> previewImpact({
    required DateTime startDate,
    required DateTime endDate,
  }) async {
    return VacationImpactPreview(
      startDate: startDate,
      endDate: endDate,
      impactedLessonCount: impactedStudentCount * 2,
      impactedStudentCount: impactedStudentCount,
      impactedStudents: List.generate(
        impactedStudentCount,
        (i) => VacationImpactedStudent(
          studentId: 'student-$i',
          studentName: '학생 $i',
          lessonCount: 2,
        ),
      ),
    );
  }

  @override
  Future<VacationPeriod> registerVacation({
    required DateTime startDate,
    required DateTime endDate,
    String? reason,
    required VacationDisposition defaultDisposition,
    Map<String, VacationDisposition>? perStudentDisposition,
  }) async {
    return _makePeriod(startDate, endDate);
  }

  @override
  Future<List<VacationPeriod>> registerVacationBatch({
    required List<VacationSegment> segments,
    String? reason,
    Map<String, VacationDisposition>? perStudentDisposition,
  }) async {
    return [_makePeriod(segments.first.startDate, segments.first.endDate)];
  }

  @override
  Future<List<VacationPeriod>> listVacations({
    bool includeCancelled = false,
  }) async => [];

  @override
  Future<VacationPeriod> cancelVacation(String periodId) async {
    throw UnimplementedError();
  }

  static VacationPeriod _makePeriod(DateTime start, DateTime end) =>
      VacationPeriod(
        id: 'vacation-001',
        teacherId: 'teacher-001',
        startDate: start,
        endDate: end,
        defaultDisposition: VacationDisposition.rollForward,
        createdAt: DateTime.now(),
      );
}

/// Repository stub that always fails on submit.
class _SubmitFailStub extends _SubmitSuccessStub {
  @override
  Future<List<VacationPeriod>> registerVacationBatch({
    required List<VacationSegment> segments,
    String? reason,
    Map<String, VacationDisposition>? perStudentDisposition,
  }) async {
    throw Exception('server error');
  }
}

// ---------------------------------------------------------------------------
// AppStrings contract tests (unit, no widget pump needed)
// ---------------------------------------------------------------------------

void main() {
  group('AppStrings.vacationNotifyDialogBody', () {
    test('N>0: N명에게 통보됨 메시지 포함', () {
      final body = AppStrings.vacationNotifyDialogBody(3);
      expect(body, contains('3'));
      expect(body, isNotEmpty);
    });

    test('N==0: 영향 학생 없음 메시지', () {
      final body = AppStrings.vacationNotifyDialogBody(0);
      expect(body, isNotEmpty);
      // Zero-impact body should NOT claim students were notified.
      expect(body.contains('0명'), isFalse);
    });

    test('제목 상수 비어 있지 않음', () {
      expect(AppStrings.vacationNotifyDialogTitle, isNotEmpty);
    });

    test('확인 버튼 상수 비어 있지 않음', () {
      expect(AppStrings.vacationNotifyDialogConfirm, isNotEmpty);
    });
  });

  // --------------------------------------------------------------------------
  // Widget tests — inject a set start/end via provider override so we can
  // bypass the date pickers (which require UI interaction) and directly
  // trigger submit.
  // --------------------------------------------------------------------------

  group('TeacherVacationModeScreen — notify dialog after submit', () {
    /// Pumps the screen with a pre-filled valid draft [2099-01-10, 2099-01-12]
    /// and the given repository stub.
    Future<void> pumpWithPrefill(
      WidgetTester tester,
      VacationRepository repo,
    ) async {
      await tester.pumpWidget(
        ProviderScope(
          overrides: [vacationRepositoryProvider.overrideWithValue(repo)],
          child: const MaterialApp(home: TeacherVacationModeScreen()),
        ),
      );
      // Pre-fill the form draft directly through the notifier.
      // pumpWidget must settle before we can call ref actions.
      await tester.pump();

      // Use the test helper to set draft dates (exposed via notifier).
      final element = tester.element(find.byType(TeacherVacationModeScreen));
      final container = ProviderScope.containerOf(element);
      final notifier = container.read(vacationFormProvider.notifier);
      notifier.setDraftStart(DateTime(2099, 1, 10));
      notifier.setDraftEnd(DateTime(2099, 1, 12));

      await tester.pumpAndSettle();
    }

    testWidgets('submit 성공 후 N명 통보 다이얼로그가 노출됨 (N>0)', (tester) async {
      await pumpWithPrefill(
        tester,
        _SubmitSuccessStub(impactedStudentCount: 3),
      );

      // Scroll to submit button and tap it.
      await tester.scrollUntilVisible(
        find.text(AppStrings.vacationRegisterButton),
        200,
        scrollable: find.byType(Scrollable).first,
      );
      await tester.pump();
      final submitBtn = find.text(AppStrings.vacationRegisterButton);
      expect(submitBtn, findsOneWidget);

      // The confirmation summary dialog appears first; confirm it.
      await tester.tap(submitBtn);
      await tester.pumpAndSettle();

      // Dismiss the summary confirmation dialog (vacationSummaryConfirm).
      final confirmSummary = find.text(AppStrings.vacationSummaryConfirm);
      if (confirmSummary.evaluate().isNotEmpty) {
        await tester.tap(confirmSummary);
        await tester.pumpAndSettle();
      }

      // Now the notify dialog should be visible.
      expect(
        find.text(AppStrings.vacationNotifyDialogTitle),
        findsOneWidget,
        reason: 'Notify dialog title must be shown after successful submit',
      );
      expect(
        find.textContaining('3'),
        findsWidgets,
        reason: 'Impacted student count (3) must appear in the dialog body',
      );

      // Dismiss the notify dialog (tap the styled button inside AlertDialog).
      await tester.tap(find.text(AppStrings.vacationNotifyDialogConfirm).last);
      await tester.pumpAndSettle();
      expect(tester.takeException(), isNull);
    });

    testWidgets('submit 실패 시 notify dialog 가 노출되지 않음', (tester) async {
      await pumpWithPrefill(tester, _SubmitFailStub());

      await tester.scrollUntilVisible(
        find.text(AppStrings.vacationRegisterButton),
        200,
        scrollable: find.byType(Scrollable).first,
      );
      await tester.pump();
      await tester.tap(find.text(AppStrings.vacationRegisterButton));
      await tester.pumpAndSettle();

      final confirmSummary = find.text(AppStrings.vacationSummaryConfirm);
      if (confirmSummary.evaluate().isNotEmpty) {
        await tester.tap(confirmSummary);
        await tester.pumpAndSettle();
      }

      // Notify dialog must NOT appear on failure.
      expect(
        find.text(AppStrings.vacationNotifyDialogTitle),
        findsNothing,
        reason: 'No notify dialog on submit failure',
      );
      expect(tester.takeException(), isNull);
    });
  });
}
