// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC17DW1uDqs-Nfe1aJUwVf6_DXWhlUzl30',
    appId: '1:434865041147:android:bd3aa4850594f483994a5e',
    messagingSenderId: '434865041147',
    projectId: 'lessonaza-d83f2',
    storageBucket: 'lessonaza-d83f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR7tRnErzgc_mYfzNxDv9zQdy2Hz7K4QQ',
    appId: '1:434865041147:ios:84849d0b4897999c994a5e',
    messagingSenderId: '434865041147',
    projectId: 'lessonaza-d83f2',
    storageBucket: 'lessonaza-d83f2.firebasestorage.app',
    iosBundleId: 'app.lessonaza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR7tRnErzgc_mYfzNxDv9zQdy2Hz7K4QQ',
    appId: '1:434865041147:ios:009863f2dacd9692994a5e',
    messagingSenderId: '434865041147',
    projectId: 'lessonaza-d83f2',
    storageBucket: 'lessonaza-d83f2.firebasestorage.app',
    iosBundleId: 'app.lessonaza.lessonaza',
  );
}
